distributionUrl=https://usw1.packages.broadcom.com/artifactory/spring-app-advisor-generic-dev-local/maven-wrapper/apache-maven-3.8.2-bin.zip
wrapperUrl=https://usw1.packages.broadcom.com/artifactory/spring-app-advisor-generic-dev-local/maven-wrapper/maven-wrapper-0.5.6.jar

