some:
  unrelated:
    property: untouched
old_snapshot_threshold: -1
trace_recovery_messages: notice
db_user_namespace: off
cluster_partition_handling: pause_minority
spring:
  rabbitmq:
    listener:
      simple:
        global-qos: true
